app:
  backend:
    replicaCount: 1
    image:
      repo: kn71026/cloud-native-backend-prod
      tag: df7133ac4c2fe9b9cef6326700c0ac3900e6116a
    service:
      type: NodePort
      port: 80
  frontend:
    replicaCount: 1
    image:
      repo: hsinlun/cloud-native-frontend-prod
      tag: 28f03d053d4e384f59f8a5bc870a7e65048218ed
    service:
      type: NodePort
      port: 80
  crawler:
    image:
      repo: royshih/cloud-native-crawler
      tag: 5b7b6cc9007a623c9f5bdabd5e2e1141fc90f536
  ingress:
    frontend:
      host: stage.ui.uccuz.online
    backend:
      host: stage.api.uccuz.online
