app:
  backend:
    replicaCount: 1
    image:
      repo: justin89721/cloud-native-backend
      tag: 51c0fd6cbace5d612ed12355d20f95ef798393ea
    service:
      type: NodePort
      port: 80
  frontend:
    replicaCount: 1
    image:
      repo: hsinlun/cloud-native-frontend-prod
      tag: 28f03d053d4e384f59f8a5bc870a7e65048218ed
    service:
      type: NodePort
      port: 80
  ingress:
    frontend:
      host: prod.ui.uccuz.online
    backend:
      host: prod.api.uccuz.online
