app:
  backend:
    replicaCount: 1
    image:
      repo: <image name>
      tag: <image tag>
    service:
      type: NodePort
      port: 80
  frontend:
    replicaCount: 1
    image:
      repo: <image name>
      tag: <image tag>
    service:
      type: NodePort
      port: 80
  ingress:
    frontend:
      host: <frontend url>
    backend:
      host: <backend url>
