app:
  backend:
    replicaCount: 1
    image:
      repo: kn71026/cloud-native-backend-prod
      tag: e2278f5fdbf90e80e8fce85dc49ef6cc56ff7809
    service:
      type: NodePort
      port: 80
  frontend:
    replicaCount: 1
    image:
      repo: hsinlun/cloud-native-frontend-prod
      tag: 28f03d053d4e384f59f8a5bc870a7e65048218ed
    service:
      type: NodePort
      port: 80
  crawler:
    image:
      repo: royshih/cloud-native-crawler
      tag: 54ae5420740867c009dd9cd3735e1be37bbba13d
  ingress:
    frontend:
      host: stage.ui.uccuz.online
    backend:
      host: stage.api.uccuz.online
