app:
  backend:
    replicaCount: 1
    image:
      repo: kn71026/cloud-native-backend-prod
      tag: 82fddf675d13a3c77cd5852d5830dcb350bbad0a
    service:
      type: NodePort
      port: 80
  frontend:
    replicaCount: 1
    image:
      repo: hsinlun/cloud-native-frontend-prod
      tag: 33779069977243808d176f01c01c81d01a96db51
    service:
      type: NodePort
      port: 80
  crawler:
    image:
      repo: royshih/cloud-native-crawler
      tag: 2a339a430d91f90d0d9119763c585eb8525604cf
  ingress:
    frontend:
      host: stage.ui.uccuz.online
    backend:
      host: stage.api.uccuz.online
