apiVersion: v1
kind: Service
metadata:
  name: cloud-native-frontend
spec:
  selector:
    app: frontend
  type: {{ .Values.app.frontend.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.frontend.service.port }}
    targetPort: 3000