apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-native-ingress
spec:
  rules:
  - host: {{ .Values.app.ingress.frontend.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-native-frontend
            port:
              number: 80
  - host: {{ .Values.app.ingress.backend.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-native-backend
            port:
              number: 80